import { Product, Category } from '@/types'

export const categories: Category[] = [
  { id: '1', slug: 'mujer', name: 'Mujer', image: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=600', count: 48 },
  { id: '2', slug: 'hombre', name: 'Hombre', image: 'https://images.unsplash.com/photo-1490578474895-699cd4e2cf59?w=600', count: 36 },
  { id: '3', slug: 'accesorios', name: 'Accesorios', image: 'https://images.unsplash.com/photo-1523779917675-b6ed3a42a561?w=600', count: 24 },
  { id: '4', slug: 'calzado', name: 'Calzado', image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600', count: 30 },
]

export const products: Product[] = [
  {
    id: '1', slug: 'vestido-floral-verano', name: 'Vestido Floral de Verano',
    price: 2499, originalPrice: 3200, category: 'mujer',
    image: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=500',
    badge: 'oferta', rating: 4.8, reviews: 124,
    description: 'Vestido ligero con estampado floral ideal para el verano. Confeccionado en tela de algodón 100% transpirable.',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Rojo', 'Azul marino', 'Blanco'],
    inStock: true,
  },
  {
    id: '2', slug: 'camisa-lino-hombre', name: 'Camisa de Lino Premium',
    price: 1899, category: 'hombre',
    image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=500',
    badge: 'nuevo', rating: 4.6, reviews: 89,
    description: 'Camisa de lino premium con corte slim fit. Perfecta para ocasiones formales e informales.',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Blanco', 'Beige', 'Celeste'],
    inStock: true,
  },
  {
    id: '3', slug: 'bolsa-cuero-tote', name: 'Bolsa Tote de Cuero',
    price: 3599, originalPrice: 4500, category: 'accesorios',
    image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=500',
    badge: 'oferta', rating: 4.9, reviews: 203,
    description: 'Bolsa tote de cuero genuino con múltiples compartimentos. Elegante y funcional.',
    colors: ['Negro', 'Camel', 'Burdeos'],
    inStock: true,
  },
  {
    id: '4', slug: 'zapatillas-running', name: 'Zapatillas Running Pro',
    price: 2999, category: 'calzado',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500',
    badge: 'popular', rating: 4.7, reviews: 312,
    description: 'Zapatillas de running con tecnología amortiguadora avanzada. Ideales para largas distancias.',
    sizes: ['36', '37', '38', '39', '40', '41', '42', '43'],
    colors: ['Negro/Blanco', 'Azul/Verde', 'Rojo/Negro'],
    inStock: true,
  },
  {
    id: '5', slug: 'jeans-skinny-mujer', name: 'Jeans Skinny Mujer',
    price: 1799, category: 'mujer',
    image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=500',
    rating: 4.5, reviews: 167,
    description: 'Jeans skinny de alta elasticidad con denim premium. Perfecto ajuste y comodidad todo el día.',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Azul oscuro', 'Negro', 'Gris'],
    inStock: true,
  },
  {
    id: '6', slug: 'chaqueta-cuero-hombre', name: 'Chaqueta de Cuero',
    price: 5990, originalPrice: 7500, category: 'hombre',
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500',
    badge: 'oferta', rating: 4.9, reviews: 78,
    description: 'Chaqueta de cuero genuino con forro interior. Estilo clásico que nunca pasa de moda.',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Negro', 'Marrón'],
    inStock: true,
  },
  {
    id: '7', slug: 'collar-dorado-mujer', name: 'Collar Dorado Elegante',
    price: 899, category: 'accesorios',
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500',
    badge: 'nuevo', rating: 4.4, reviews: 56,
    description: 'Collar chapado en oro de 18k con dije en forma de luna. Hipoalergénico.',
    colors: ['Dorado', 'Plateado'],
    inStock: true,
  },
  {
    id: '8', slug: 'botas-cuero-mujer', name: 'Botas de Cuero Mujer',
    price: 4299, category: 'calzado',
    image: 'https://images.unsplash.com/photo-1605812860427-4024433a70fd?w=500',
    badge: 'popular', rating: 4.8, reviews: 145,
    description: 'Botas de cuero genuino con tacón cómodo. Perfectas para el otoño e invierno.',
    sizes: ['35', '36', '37', '38', '39', '40'],
    colors: ['Negro', 'Marrón oscuro'],
    inStock: false,
  },
]

export const featuredProducts = products.filter(p => p.badge !== undefined).slice(0, 4)
