import type { EditorTree } from "@/types/editor";

type ConstructorPresetId =
  | "home"
  | "platform"
  | "pricing"
  | "contact"
  | "faq"
  | "services"
  | "process"
  | "portfolio";

const LEGACY_PRESET_ALIASES: Record<string, ConstructorPresetId> = {
  "index.html": "home",
  "plataforma/index.html": "platform",
  "precios/index.html": "pricing",
  "contacto/index.html": "contact",
  "faq/index.html": "faq",
  "servicios/index.html": "services",
  "proceso/index.html": "process",
  "portafolio/index.html": "portfolio",
};

const PRESET_PREVIEW_PATHS: Record<ConstructorPresetId, string> = {
  home: "/",
  platform: "/plataforma",
  pricing: "/precios",
  contact: "/contacto",
  faq: "/faq",
  services: "/servicios",
  process: "/proceso",
  portfolio: "/portafolio",
};

const PRESET_TREES: Record<ConstructorPresetId, EditorTree> = {
  home: {
    rootId: "root",
    nodes: {
      root: {
        id: "root",
        type: "section",
        props: { maxWidth: "full", paddingY: "none", paddingX: "none", align: "left", background: "#112540" },
        children: ["home-hero", "home-stats", "home-features", "home-pricing", "home-cta"],
        version: 1,
      },

      // ── Hero ─────────────────────────────────────────────────────────
      "home-hero": {
        id: "home-hero",
        type: "section",
        props: {
          maxWidth: "xl",
          paddingY: "xl",
          paddingX: "md",
          align: "left",
          background: "linear-gradient(180deg, #0f2240 0%, #172f52 100%)",
        },
        children: ["home-eyebrow", "home-title", "home-copy", "home-btn-primary", "home-btn-outline"],
        version: 1,
        displayName: "Hero principal",
      },
      "home-eyebrow": {
        id: "home-eyebrow",
        type: "text",
        props: { content: "Plataforma SaaS · Activa ahora mismo", size: "sm", color: "#00b5f6", align: "left" },
        children: [],
        version: 1,
      },
      "home-title": {
        id: "home-title",
        type: "heading",
        props: { text: "Tu negocio digital, todo en un panel", level: 1, size: "5xl", weight: "extrabold", color: "#ffffff", align: "left" },
        children: [],
        version: 1,
      },
      "home-copy": {
        id: "home-copy",
        type: "text",
        props: {
          content: "Web profesional + panel privado + gestión de clientes + almacenamiento en la nube. Todo incluido, sin instalar nada, activo en menos de 24 horas.",
          size: "lg", color: "#cbd5e1", align: "left", maxWidth: "lg",
        },
        children: [],
        version: 1,
      },
      "home-btn-primary": {
        id: "home-btn-primary",
        type: "ctaButton",
        props: { label: "Ver planes desde $349/mes →", href: "/precios", variant: "primary" },
        children: [],
        version: 1,
      },
      "home-btn-outline": {
        id: "home-btn-outline",
        type: "ctaButton",
        props: { label: "Ver demos en vivo", href: "/webs", variant: "secondary" },
        children: [],
        version: 1,
      },

      // ── Stats ─────────────────────────────────────────────────────────
      "home-stats": {
        id: "home-stats",
        type: "section",
        props: { maxWidth: "xl", paddingY: "md", paddingX: "md", align: "left", background: "#112540" },
        children: ["home-stats-title", "home-stat-1", "home-stat-2", "home-stat-3"],
        version: 1,
        displayName: "Estadísticas",
      },
      "home-stats-title": {
        id: "home-stats-title",
        type: "text",
        props: { content: "Números que respaldan nuestra plataforma", size: "sm", color: "#475569", align: "left" },
        children: [],
        version: 1,
      },
      "home-stat-1": {
        id: "home-stat-1",
        type: "heading",
        props: { text: "150+ proyectos completados", level: 3, size: "xl", weight: "bold", color: "#00b5f6", align: "left" },
        children: [],
        version: 1,
      },
      "home-stat-2": {
        id: "home-stat-2",
        type: "heading",
        props: { text: "99.9% uptime garantizado", level: 3, size: "xl", weight: "bold", color: "#00b5f6", align: "left" },
        children: [],
        version: 1,
      },
      "home-stat-3": {
        id: "home-stat-3",
        type: "heading",
        props: { text: "24h de tiempo de activación", level: 3, size: "xl", weight: "bold", color: "#00b5f6", align: "left" },
        children: [],
        version: 1,
      },

      // ── Features ──────────────────────────────────────────────────────
      "home-features": {
        id: "home-features",
        type: "section",
        props: { maxWidth: "xl", paddingY: "xl", paddingX: "md", align: "center", background: "#112540" },
        children: [
          "home-feat-tag", "home-feat-title", "home-feat-desc",
          "home-feat-1-title", "home-feat-1-copy",
          "home-feat-2-title", "home-feat-2-copy",
          "home-feat-3-title", "home-feat-3-copy",
          "home-feat-4-title", "home-feat-4-copy",
          "home-feat-5-title", "home-feat-5-copy",
          "home-feat-6-title", "home-feat-6-copy",
        ],
        version: 1,
        displayName: "Características incluidas",
      },
      "home-feat-tag": {
        id: "home-feat-tag",
        type: "text",
        props: { content: "Características", size: "sm", color: "#00b5f6", align: "center" },
        children: [],
        version: 1,
      },
      "home-feat-title": {
        id: "home-feat-title",
        type: "heading",
        props: { text: "Todo incluido en tu plataforma", level: 2, size: "4xl", weight: "bold", color: "#ffffff", align: "center" },
        children: [],
        version: 1,
      },
      "home-feat-desc": {
        id: "home-feat-desc",
        type: "text",
        props: { content: "Un ecosistema completo para operar tu negocio digital. Sin contratar herramientas por separado, sin configuraciones complejas.", size: "md", color: "#94a3b8", align: "center", maxWidth: "lg" },
        children: [],
        version: 1,
      },
      "home-feat-1-title": {
        id: "home-feat-1-title",
        type: "heading",
        props: { text: "🌐 Sitio Web Incluido", level: 3, size: "xl", weight: "semibold", color: "#ffffff", align: "left" },
        children: [],
        version: 1,
      },
      "home-feat-1-copy": {
        id: "home-feat-1-copy",
        type: "text",
        props: { content: "Tu presencia digital profesional lista desde el primer día. Diseño responsive, optimizado para SEO y velocidad de carga máxima. Hosting · SSL · SEO", size: "sm", color: "#94a3b8", align: "left" },
        children: [],
        version: 1,
      },
      "home-feat-2-title": {
        id: "home-feat-2-title",
        type: "heading",
        props: { text: "🔐 Panel de Control", level: 3, size: "xl", weight: "semibold", color: "#ffffff", align: "left" },
        children: [],
        version: 1,
      },
      "home-feat-2-copy": {
        id: "home-feat-2-copy",
        type: "text",
        props: { content: "Dashboard privado con tu propio subdominio. Gestiona clientes, archivos y proyectos desde un solo lugar, sin instalar nada. Dashboard · Roles · Accesos", size: "sm", color: "#94a3b8", align: "left" },
        children: [],
        version: 1,
      },
      "home-feat-3-title": {
        id: "home-feat-3-title",
        type: "heading",
        props: { text: "☁️ Almacenamiento en la Nube", level: 3, size: "xl", weight: "semibold", color: "#ffffff", align: "left" },
        children: [],
        version: 1,
      },
      "home-feat-3-copy": {
        id: "home-feat-3-copy",
        type: "text",
        props: { content: "Sube, organiza y comparte documentos, contratos e imágenes con tus clientes de forma segura y ordenada. Cloud · Backups · Cifrado", size: "sm", color: "#94a3b8", align: "left" },
        children: [],
        version: 1,
      },
      "home-feat-4-title": {
        id: "home-feat-4-title",
        type: "heading",
        props: { text: "👥 Gestión de Clientes", level: 3, size: "xl", weight: "semibold", color: "#ffffff", align: "left" },
        children: [],
        version: 1,
      },
      "home-feat-4-copy": {
        id: "home-feat-4-copy",
        type: "text",
        props: { content: "Crea portales individuales para cada cliente. Ellos acceden solo a lo que les corresponde, tú controlas todo desde tu panel. CRM · Portales · Permisos", size: "sm", color: "#94a3b8", align: "left" },
        children: [],
        version: 1,
      },
      "home-feat-5-title": {
        id: "home-feat-5-title",
        type: "heading",
        props: { text: "📊 Analíticas en Tiempo Real", level: 3, size: "xl", weight: "semibold", color: "#ffffff", align: "left" },
        children: [],
        version: 1,
      },
      "home-feat-5-copy": {
        id: "home-feat-5-copy",
        type: "text",
        props: { content: "Visualiza métricas de tu negocio, actividad de clientes y uso de almacenamiento. Toma decisiones basadas en datos reales. Dashboard · Reportes · KPIs", size: "sm", color: "#94a3b8", align: "left" },
        children: [],
        version: 1,
      },
      "home-feat-6-title": {
        id: "home-feat-6-title",
        type: "heading",
        props: { text: "🔒 Seguridad 24/7", level: 3, size: "xl", weight: "semibold", color: "#ffffff", align: "left" },
        children: [],
        version: 1,
      },
      "home-feat-6-copy": {
        id: "home-feat-6-copy",
        type: "text",
        props: { content: "SSL incluido, autenticación de dos factores, backups automáticos diarios y monitoreo continuo de tu infraestructura. SSL · 2FA · Uptime 99.9%", size: "sm", color: "#94a3b8", align: "left" },
        children: [],
        version: 1,
      },

      // ── Pricing ───────────────────────────────────────────────────────
      "home-pricing": {
        id: "home-pricing",
        type: "section",
        props: { maxWidth: "xl", paddingY: "xl", paddingX: "md", align: "center", background: "#172f52" },
        children: ["home-price-tag", "home-price-title", "home-price-desc", "home-plan-basic", "home-plan-pro", "home-plan-enterprise"],
        version: 1,
        displayName: "Planes y precios",
      },
      "home-price-tag": {
        id: "home-price-tag",
        type: "text",
        props: { content: "Precios", size: "sm", color: "#00b5f6", align: "center" },
        children: [],
        version: 1,
      },
      "home-price-title": {
        id: "home-price-title",
        type: "heading",
        props: { text: "Planes claros, sin sorpresas", level: 2, size: "4xl", weight: "bold", color: "#ffffff", align: "center" },
        children: [],
        version: 1,
      },
      "home-price-desc": {
        id: "home-price-desc",
        type: "text",
        props: { content: "Elige el plan que mejor se adapte a tu negocio. Todos incluyen soporte, SSL y hosting.", size: "md", color: "#94a3b8", align: "center", maxWidth: "lg" },
        children: [],
        version: 1,
      },
      "home-plan-basic": {
        id: "home-plan-basic",
        type: "section",
        props: { maxWidth: "sm", paddingY: "lg", paddingX: "md", align: "left", background: "linear-gradient(180deg, rgba(255,255,255,0.035), rgba(255,255,255,0.02))", border: "1px solid rgba(0,181,246,0.14)", boxShadow: "0 16px 40px rgba(0,0,0,0.18)", borderRadius: "xl" },
        children: ["home-plan-basic-name", "home-plan-basic-price", "home-plan-basic-desc", "home-plan-basic-btn"],
        version: 1,
        displayName: "Plan Básico",
      },
      "home-plan-basic-name": {
        id: "home-plan-basic-name",
        type: "heading",
        props: { text: "Básico", level: 3, size: "2xl", weight: "bold", color: "#ffffff", align: "left" },
        children: [],
        version: 1,
      },
      "home-plan-basic-price": {
        id: "home-plan-basic-price",
        type: "heading",
        props: { text: "$349/mes", level: 2, size: "3xl", weight: "extrabold", color: "#00b5f6", align: "left" },
        children: [],
        version: 1,
      },
      "home-plan-basic-desc": {
        id: "home-plan-basic-desc",
        type: "text",
        props: { content: "Sitio web profesional + panel privado + hasta 5 clientes + 10 GB almacenamiento.", size: "sm", color: "#94a3b8", align: "left" },
        children: [],
        version: 1,
      },
      "home-plan-basic-btn": {
        id: "home-plan-basic-btn",
        type: "ctaButton",
        props: { label: "Elegir Básico", href: "/precios", variant: "secondary" },
        children: [],
        version: 1,
      },
      "home-plan-pro": {
        id: "home-plan-pro",
        type: "section",
        props: { maxWidth: "sm", paddingY: "lg", paddingX: "md", align: "left", background: "linear-gradient(135deg, rgba(0,181,246,0.12) 0%, rgba(0,131,179,0.08) 100%)", border: "1px solid rgba(0,181,246,0.28)", boxShadow: "0 0 40px rgba(0,181,246,0.10)", borderRadius: "xl" },
        children: ["home-plan-pro-name", "home-plan-pro-price", "home-plan-pro-desc", "home-plan-pro-btn"],
        version: 1,
        displayName: "Plan Pro",
      },
      "home-plan-pro-name": {
        id: "home-plan-pro-name",
        type: "heading",
        props: { text: "Pro ⭐ Más popular", level: 3, size: "2xl", weight: "bold", color: "#ffffff", align: "left" },
        children: [],
        version: 1,
      },
      "home-plan-pro-price": {
        id: "home-plan-pro-price",
        type: "heading",
        props: { text: "$649/mes", level: 2, size: "3xl", weight: "extrabold", color: "#00b5f6", align: "left" },
        children: [],
        version: 1,
      },
      "home-plan-pro-desc": {
        id: "home-plan-pro-desc",
        type: "text",
        props: { content: "Todo lo de Básico + clientes ilimitados + 50 GB + tienda en línea + analíticas avanzadas.", size: "sm", color: "#cbd5e1", align: "left" },
        children: [],
        version: 1,
      },
      "home-plan-pro-btn": {
        id: "home-plan-pro-btn",
        type: "ctaButton",
        props: { label: "Elegir Pro", href: "/precios", variant: "primary" },
        children: [],
        version: 1,
      },
      "home-plan-enterprise": {
        id: "home-plan-enterprise",
        type: "section",
        props: { maxWidth: "sm", paddingY: "lg", paddingX: "md", align: "left", background: "linear-gradient(180deg, rgba(255,255,255,0.035), rgba(255,255,255,0.02))", border: "1px solid rgba(0,181,246,0.14)", boxShadow: "0 16px 40px rgba(0,0,0,0.18)", borderRadius: "xl" },
        children: ["home-plan-ent-name", "home-plan-ent-price", "home-plan-ent-desc", "home-plan-ent-btn"],
        version: 1,
        displayName: "Plan Empresa",
      },
      "home-plan-ent-name": {
        id: "home-plan-ent-name",
        type: "heading",
        props: { text: "Empresa", level: 3, size: "2xl", weight: "bold", color: "#ffffff", align: "left" },
        children: [],
        version: 1,
      },
      "home-plan-ent-price": {
        id: "home-plan-ent-price",
        type: "heading",
        props: { text: "Personalizado", level: 2, size: "3xl", weight: "extrabold", color: "#00b5f6", align: "left" },
        children: [],
        version: 1,
      },
      "home-plan-ent-desc": {
        id: "home-plan-ent-desc",
        type: "text",
        props: { content: "Infraestructura dedicada, SLA garantizado, soporte prioritario e integraciones a medida.", size: "sm", color: "#94a3b8", align: "left" },
        children: [],
        version: 1,
      },
      "home-plan-ent-btn": {
        id: "home-plan-ent-btn",
        type: "ctaButton",
        props: { label: "Contactar ventas", href: "/contacto", variant: "secondary" },
        children: [],
        version: 1,
      },

      // ── CTA final ─────────────────────────────────────────────────────
      "home-cta": {
        id: "home-cta",
        type: "section",
        props: { maxWidth: "lg", paddingY: "xl", paddingX: "md", align: "center", background: "linear-gradient(180deg, rgba(255,255,255,0.035), rgba(255,255,255,0.02))", border: "1px solid rgba(0,181,246,0.14)", boxShadow: "0 16px 40px rgba(0,0,0,0.18)", borderRadius: "xl" },
        children: ["home-cta-title", "home-cta-copy", "home-cta-button"],
        version: 1,
        displayName: "CTA final",
      },
      "home-cta-title": {
        id: "home-cta-title",
        type: "heading",
        props: { text: "¿Listo para empezar?", level: 2, size: "3xl", weight: "bold", color: "#ffffff", align: "center" },
        children: [],
        version: 1,
      },
      "home-cta-copy": {
        id: "home-cta-copy",
        type: "text",
        props: { content: "Activa tu plataforma hoy. Nuestro equipo la deja lista en menos de 24 horas.", size: "md", color: "#cbd5e1", align: "center", maxWidth: "md" },
        children: [],
        version: 1,
      },
      "home-cta-button": {
        id: "home-cta-button",
        type: "ctaButton",
        props: { label: "Elegir mi plan →", href: "/precios", variant: "primary" },
        children: [],
        version: 1,
      },
    },
    theme: {
      colors: { primary: "#112540", secondary: "#00b5f6", background: "#112540", text: "#ffffff", accent: "#00b5f6" },
      fontHeading: "Inter, sans-serif",
      fontBody: "Inter, sans-serif",
    },
    seo: {
      title: "Orvenix — Plataforma SaaS para tu Negocio Digital",
      description: "Plataforma SaaS todo-en-uno: sitio web, panel privado, clientes y almacenamiento. Sin instalar nada. Activo en 24h.",
      keywords: "saas, constructor, orvenix, panel, clientes, almacenamiento",
      ogImage: "/img/logo.png",
    },
  },
  platform: {
    rootId: "root",
    nodes: {
      root: {
        id: "root",
        type: "section",
        props: {
          maxWidth: "full",
          paddingY: "none",
          paddingX: "none",
          align: "left",
          background: "#112540",
        },
        children: ["platform-hero", "platform-links", "platform-plans"],
        version: 1,
      },
      "platform-hero": {
        id: "platform-hero",
        type: "section",
        props: {
          maxWidth: "xl",
          paddingY: "xl",
          paddingX: "md",
          align: "left",
          background: "#172f52",
        },
        children: ["platform-eyebrow", "platform-title", "platform-copy", "platform-button"],
        version: 1,
        displayName: "Hero plataforma",
      },
      "platform-eyebrow": {
        id: "platform-eyebrow",
        type: "text",
        props: {
          content: "Plataforma integrada",
          size: "sm",
          color: "#00b5f6",
          align: "left",
        },
        children: [],
        version: 1,
      },
      "platform-title": {
        id: "platform-title",
        type: "heading",
        props: {
          text: "Tu sitio y tu panel en un solo sistema",
          level: 1,
          size: "5xl",
          weight: "extrabold",
          color: "#ffffff",
          align: "left",
        },
        children: [],
        version: 1,
      },
      "platform-copy": {
        id: "platform-copy",
        type: "text",
        props: {
          content: "Tu sitio web y tu panel de control en un solo ecosistema. Gestiona clientes, archivos y métricas desde un solo lugar, sin instalar nada.",
          size: "lg",
          color: "#cbd5e1",
          align: "left",
          maxWidth: "lg",
        },
        children: [],
        version: 1,
      },
      "platform-button": {
        id: "platform-button",
        type: "ctaButton",
        props: {
          label: "Crear cuenta",
          href: "/register",
          variant: "primary",
        },
        children: [],
        version: 1,
      },
      "platform-links": {
        id: "platform-links",
        type: "section",
        props: {
          maxWidth: "xl",
          paddingY: "lg",
          paddingX: "md",
          align: "left",
          background: "#112540",
        },
        children: ["platform-links-title", "platform-links-copy"],
        version: 1,
        displayName: "Accesos rapidos",
      },
      "platform-links-title": {
        id: "platform-links-title",
        type: "heading",
        props: {
          text: "Accesos y verticales del sistema",
          level: 2,
          size: "3xl",
          weight: "bold",
          color: "#ffffff",
          align: "left",
        },
        children: [],
        version: 1,
      },
      "platform-links-copy": {
        id: "platform-links-copy",
        type: "text",
        props: {
          content: "Desde aquí puedes dirigir al dashboard, plantillas, demos SaaS y servicio profesional.",
          size: "md",
          color: "#94a3b8",
          align: "left",
          maxWidth: "lg",
        },
        children: [],
        version: 1,
      },
      "platform-plans": {
        id: "platform-plans",
        type: "section",
        props: {
          maxWidth: "xl",
          paddingY: "lg",
          paddingX: "md",
          align: "left",
          background: "#112540",
        },
        children: ["platform-plans-title", "platform-plans-copy"],
        version: 1,
        displayName: "Planes",
      },
      "platform-plans-title": {
        id: "platform-plans-title",
        type: "heading",
        props: {
          text: "Planes para activar tu plataforma",
          level: 2,
          size: "3xl",
          weight: "bold",
          color: "#ffffff",
          align: "left",
        },
        children: [],
        version: 1,
      },
      "platform-plans-copy": {
        id: "platform-plans-copy",
        type: "text",
        props: {
          content: "Accede al dashboard de clientes, plantillas de sitios web, demos en vivo de cada vertical SaaS y nuestro servicio de diseño profesional.",
          size: "md",
          color: "#94a3b8",
          align: "left",
          maxWidth: "lg",
        },
        children: [],
        version: 1,
      },
    },
  },
  pricing: {
    rootId: "root",
    nodes: {
      root: {
        id: "root",
        type: "section",
        props: { maxWidth: "full", paddingY: "none", paddingX: "none", align: "left", background: "#112540" },
        children: ["pricing-hero", "pricing-summary"],
        version: 1,
      },
      "pricing-hero": {
        id: "pricing-hero",
        type: "section",
        props: { maxWidth: "xl", paddingY: "xl", paddingX: "md", align: "left", background: "#172f52" },
        children: ["pricing-title", "pricing-copy", "pricing-button"],
        version: 1,
        displayName: "Hero precios",
      },
      "pricing-title": {
        id: "pricing-title",
        type: "heading",
        props: { text: "Planes claros para activar tu negocio", level: 1, size: "5xl", weight: "extrabold", color: "#ffffff", align: "left" },
        children: [],
        version: 1,
      },
      "pricing-copy": {
        id: "pricing-copy",
        type: "text",
        props: { content: "Tres planes pensados para cada etapa de tu negocio. Desde el emprendedor individual hasta la empresa con decenas de clientes. Sin contratos forzosos, cancela cuando quieras.", size: "lg", color: "#cbd5e1", align: "left", maxWidth: "lg" },
        children: [],
        version: 1,
      },
      "pricing-button": {
        id: "pricing-button",
        type: "ctaButton",
        props: { label: "Elegir plan", href: "/register", variant: "primary" },
        children: [],
        version: 1,
      },
      "pricing-summary": {
        id: "pricing-summary",
        type: "section",
        props: { maxWidth: "lg", paddingY: "lg", paddingX: "md", align: "left", background: "linear-gradient(180deg, rgba(255,255,255,0.035), rgba(255,255,255,0.02))", border: "1px solid rgba(0,181,246,0.14)", boxShadow: "0 16px 40px rgba(0,0,0,0.18)", borderRadius: "xl" },
        children: ["pricing-summary-title", "pricing-summary-copy"],
        version: 1,
        displayName: "Resumen precios",
      },
      "pricing-summary-title": {
        id: "pricing-summary-title",
        type: "heading",
        props: { text: "Básico, Pro y Empresa", level: 2, size: "3xl", weight: "bold", color: "#ffffff", align: "left" },
        children: [],
        version: 1,
      },
      "pricing-summary-copy": {
        id: "pricing-summary-copy",
        type: "text",
        props: { content: "Básico desde $349/mes · Pro desde $649/mes · Empresa con precio personalizado. Todos incluyen hosting, SSL, soporte y activación en menos de 24h. Precios antes de IVA (16%).", size: "md", color: "#94a3b8", align: "left", maxWidth: "lg" },
        children: [],
        version: 1,
      },
    },
  },
  contact: {
    rootId: "root",
    nodes: {
      root: {
        id: "root",
        type: "section",
        props: { maxWidth: "full", paddingY: "none", paddingX: "none", align: "left", background: "#112540" },
        children: ["contact-hero", "contact-form"],
        version: 1,
      },
      "contact-hero": {
        id: "contact-hero",
        type: "section",
        props: { maxWidth: "xl", paddingY: "xl", paddingX: "md", align: "left", background: "#172f52" },
        children: ["contact-title", "contact-copy"],
        version: 1,
        displayName: "Hero contacto",
      },
      "contact-title": {
        id: "contact-title",
        type: "heading",
        props: { text: "Hablemos de tu proyecto", level: 1, size: "5xl", weight: "extrabold", color: "#ffffff", align: "left" },
        children: [],
        version: 1,
      },
      "contact-copy": {
        id: "contact-copy",
        type: "text",
        props: { content: "Cuéntanos sobre tu proyecto y te respondemos en menos de 24 horas. Sin compromiso, sin presión. También puedes agendar una llamada directamente con nuestro equipo.", size: "lg", color: "#cbd5e1", align: "left", maxWidth: "lg" },
        children: [],
        version: 1,
      },
      "contact-form": {
        id: "contact-form",
        type: "section",
        props: { maxWidth: "lg", paddingY: "lg", paddingX: "md", align: "left", background: "linear-gradient(180deg, rgba(255,255,255,0.035), rgba(255,255,255,0.02))", border: "1px solid rgba(0,181,246,0.14)", boxShadow: "0 16px 40px rgba(0,0,0,0.18)", borderRadius: "xl" },
        children: ["contact-form-title", "contact-form-copy", "contact-form-button"],
        version: 1,
        displayName: "CTA contacto",
      },
      "contact-form-title": {
        id: "contact-form-title",
        type: "heading",
        props: { text: "Agenda una llamada", level: 2, size: "3xl", weight: "bold", color: "#ffffff", align: "left" },
        children: [],
        version: 1,
      },
      "contact-form-copy": {
        id: "contact-form-copy",
        type: "text",
        props: { content: "Escríbenos a hola@orvenix.com.mx · WhatsApp disponible en horario comercial · Tiempo de respuesta promedio: 2 horas. Para proyectos urgentes podemos activar en el mismo día.", size: "md", color: "#94a3b8", align: "left", maxWidth: "lg" },
        children: [],
        version: 1,
      },
      "contact-form-button": {
        id: "contact-form-button",
        type: "ctaButton",
        props: { label: "Solicitar demo", href: "/contacto", variant: "secondary" },
        children: [],
        version: 1,
      },
    },
  },
  faq: {
    rootId: "root",
    nodes: {
      root: {
        id: "root",
        type: "section",
        props: { maxWidth: "full", paddingY: "none", paddingX: "none", align: "left", background: "#112540" },
        children: ["faq-hero", "faq-body"],
        version: 1,
      },
      "faq-hero": {
        id: "faq-hero",
        type: "section",
        props: { maxWidth: "xl", paddingY: "xl", paddingX: "md", align: "left", background: "#172f52" },
        children: ["faq-title", "faq-copy"],
        version: 1,
        displayName: "Hero FAQ",
      },
      "faq-title": {
        id: "faq-title",
        type: "heading",
        props: { text: "Preguntas frecuentes", level: 1, size: "5xl", weight: "extrabold", color: "#ffffff", align: "left" },
        children: [],
        version: 1,
      },
      "faq-copy": {
        id: "faq-copy",
        type: "text",
        props: { content: "Resolvemos las dudas más comunes sobre nuestra plataforma. Si no encuentras lo que buscas, escríbenos directamente y te ayudamos.", size: "lg", color: "#cbd5e1", align: "left", maxWidth: "lg" },
        children: [],
        version: 1,
      },
      "faq-body": {
        id: "faq-body",
        type: "section",
        props: { maxWidth: "lg", paddingY: "lg", paddingX: "md", align: "left", background: "linear-gradient(180deg, rgba(255,255,255,0.035), rgba(255,255,255,0.02))", border: "1px solid rgba(0,181,246,0.14)", boxShadow: "0 16px 40px rgba(0,0,0,0.18)", borderRadius: "xl" },
        children: ["faq-body-title", "faq-body-copy"],
        version: 1,
        displayName: "FAQ body",
      },
      "faq-body-title": {
        id: "faq-body-title",
        type: "heading",
        props: { text: "Base lista para preguntas y respuestas", level: 2, size: "3xl", weight: "bold", color: "#ffffff", align: "left" },
        children: [],
        version: 1,
      },
      "faq-body-copy": {
        id: "faq-body-copy",
        type: "text",
        props: { content: "¿Necesito conocimientos técnicos? No. ¿Puedo conectar mi dominio? Sí. ¿Cuántos clientes puedo agregar? Depende del plan. ¿Hay garantía de devolución? 30 días sin preguntas.", size: "md", color: "#94a3b8", align: "left", maxWidth: "lg" },
        children: [],
        version: 1,
      },
    },
  },
  services: {
    rootId: "root",
    nodes: {
      root: {
        id: "root",
        type: "section",
        props: { maxWidth: "full", paddingY: "none", paddingX: "none", align: "left", background: "#112540" },
        children: ["services-hero", "services-grid", "services-compare", "services-cta"],
        version: 1,
      },
      "services-hero": {
        id: "services-hero",
        type: "section",
        props: { maxWidth: "xl", paddingY: "xl", paddingX: "md", align: "left", background: "#172f52" },
        children: ["services-eyebrow", "services-title", "services-copy", "services-button"],
        version: 1,
        displayName: "Hero servicios",
      },
      "services-eyebrow": {
        id: "services-eyebrow",
        type: "text",
        props: { content: "Plataforma todo-en-uno", size: "sm", color: "#00b5f6", align: "left" },
        children: [],
        version: 1,
      },
      "services-title": {
        id: "services-title",
        type: "heading",
        props: { text: "Todo lo que necesita tu negocio en un panel", level: 1, size: "5xl", weight: "extrabold", color: "#ffffff", align: "left" },
        children: [],
        version: 1,
      },
      "services-copy": {
        id: "services-copy",
        type: "text",
        props: {
          content: "Panel privado, sitio web profesional, tienda en línea, agenda de citas, almacenamiento en la nube y analíticas en tiempo real. Todo incluido en un solo panel, listo en menos de 24 horas.",
          size: "lg",
          color: "#cbd5e1",
          align: "left",
          maxWidth: "lg",
        },
        children: [],
        version: 1,
      },
      "services-button": {
        id: "services-button",
        type: "ctaButton",
        props: { label: "Ver planes", href: "/precios", variant: "primary" },
        children: [],
        version: 1,
      },
      "services-grid": {
        id: "services-grid",
        type: "section",
        props: { maxWidth: "xl", paddingY: "lg", paddingX: "md", align: "left", background: "#112540" },
        children: ["services-grid-title", "services-grid-copy"],
        version: 1,
        displayName: "Bloques de caracteristicas",
      },
      "services-grid-title": {
        id: "services-grid-title",
        type: "heading",
        props: { text: "Caracteristicas base del sistema", level: 2, size: "3xl", weight: "bold", color: "#ffffff", align: "left" },
        children: [],
        version: 1,
      },
      "services-grid-copy": {
        id: "services-grid-copy",
        type: "text",
        props: {
          content: "Cada módulo funciona de forma independiente y se integra con los demás. Activa solo lo que necesitas hoy y agrega más cuando tu negocio crezca.",
          size: "md",
          color: "#94a3b8",
          align: "left",
          maxWidth: "lg",
        },
        children: [],
        version: 1,
      },
      "services-compare": {
        id: "services-compare",
        type: "section",
        props: { maxWidth: "xl", paddingY: "lg", paddingX: "md", align: "left", background: "linear-gradient(180deg, rgba(255,255,255,0.035), rgba(255,255,255,0.02))", border: "1px solid rgba(0,181,246,0.14)", boxShadow: "0 16px 40px rgba(0,0,0,0.18)", borderRadius: "xl" },
        children: ["services-compare-title", "services-compare-copy"],
        version: 1,
        displayName: "Comparativa de planes",
      },
      "services-compare-title": {
        id: "services-compare-title",
        type: "heading",
        props: { text: "Resumen listo para comparar planes", level: 2, size: "3xl", weight: "bold", color: "#ffffff", align: "left" },
        children: [],
        version: 1,
      },
      "services-compare-copy": {
        id: "services-compare-copy",
        type: "text",
        props: {
          content: "Compara Básico, Pro y Empresa en una sola vista. Todos los planes incluyen sitio web, panel privado, SSL, hosting y soporte. Sin contratos a largo plazo.",
          size: "md",
          color: "#94a3b8",
          align: "left",
          maxWidth: "lg",
        },
        children: [],
        version: 1,
      },
      "services-cta": {
        id: "services-cta",
        type: "section",
        props: { maxWidth: "lg", paddingY: "lg", paddingX: "md", align: "center", background: "#172f52", borderRadius: "xl" },
        children: ["services-cta-title", "services-cta-copy", "services-cta-button"],
        version: 1,
        displayName: "CTA final",
      },
      "services-cta-title": {
        id: "services-cta-title",
        type: "heading",
        props: { text: "Activa tu plataforma hoy", level: 2, size: "3xl", weight: "bold", color: "#ffffff", align: "center" },
        children: [],
        version: 1,
      },
      "services-cta-copy": {
        id: "services-cta-copy",
        type: "text",
        props: { content: "Nuestro equipo te deja la plataforma lista en menos de 24 horas. Sin costos ocultos, sin configuraciones complejas.", size: "md", color: "#cbd5e1", align: "center", maxWidth: "md" },
        children: [],
        version: 1,
      },
      "services-cta-button": {
        id: "services-cta-button",
        type: "ctaButton",
        props: { label: "Solicitar demo", href: "/contacto", variant: "secondary" },
        children: [],
        version: 1,
      },
    },
  },
  process: {
    rootId: "root",
    nodes: {
      root: {
        id: "root",
        type: "section",
        props: { maxWidth: "full", paddingY: "none", paddingX: "none", align: "left", background: "#112540" },
        children: ["process-hero", "process-steps", "process-guarantees", "process-timeline"],
        version: 1,
      },
      "process-hero": {
        id: "process-hero",
        type: "section",
        props: { maxWidth: "xl", paddingY: "xl", paddingX: "md", align: "center", background: "#172f52" },
        children: ["process-eyebrow", "process-title", "process-copy"],
        version: 1,
        displayName: "Hero proceso",
      },
      "process-eyebrow": {
        id: "process-eyebrow",
        type: "text",
        props: { content: "Metodologia agil probada", size: "sm", color: "#00b5f6", align: "center" },
        children: [],
        version: 1,
      },
      "process-title": {
        id: "process-title",
        type: "heading",
        props: { text: "Como llevamos tu idea al exito", level: 1, size: "5xl", weight: "extrabold", color: "#ffffff", align: "center" },
        children: [],
        version: 1,
      },
      "process-copy": {
        id: "process-copy",
        type: "text",
        props: { content: "Discovery, diseño, desarrollo, pruebas y soporte. Un flujo probado en más de 150 proyectos para que tu plataforma esté lista en el menor tiempo posible.", size: "lg", color: "#cbd5e1", align: "center", maxWidth: "lg" },
        children: [],
        version: 1,
      },
      "process-steps": {
        id: "process-steps",
        type: "section",
        props: { maxWidth: "xl", paddingY: "lg", paddingX: "md", align: "left", background: "#112540" },
        children: ["process-steps-title", "process-steps-copy"],
        version: 1,
        displayName: "Pasos",
      },
      "process-steps-title": {
        id: "process-steps-title",
        type: "heading",
        props: { text: "Base editable para discovery, diseno, desarrollo y soporte", level: 2, size: "3xl", weight: "bold", color: "#ffffff", align: "left" },
        children: [],
        version: 1,
      },
      "process-steps-copy": {
        id: "process-steps-copy",
        type: "text",
        props: { content: "Paso 1: Reunión de discovery (30 min). Paso 2: Propuesta y diseño (24-48h). Paso 3: Desarrollo e integración (3-7 días). Paso 4: Pruebas y ajustes. Paso 5: Entrega y soporte.", size: "md", color: "#94a3b8", align: "left", maxWidth: "lg" },
        children: [],
        version: 1,
      },
      "process-guarantees": {
        id: "process-guarantees",
        type: "section",
        props: { maxWidth: "xl", paddingY: "lg", paddingX: "md", align: "left", background: "linear-gradient(180deg, rgba(255,255,255,0.035), rgba(255,255,255,0.02))", border: "1px solid rgba(0,181,246,0.14)", boxShadow: "0 16px 40px rgba(0,0,0,0.18)", borderRadius: "xl" },
        children: ["process-guarantees-title", "process-guarantees-copy"],
        version: 1,
        displayName: "Garantias",
      },
      "process-guarantees-title": {
        id: "process-guarantees-title",
        type: "heading",
        props: { text: "Garantias de calidad listas para personalizar", level: 2, size: "3xl", weight: "bold", color: "#ffffff", align: "left" },
        children: [],
        version: 1,
      },
      "process-guarantees-copy": {
        id: "process-guarantees-copy",
        type: "text",
        props: { content: "Garantía de devolución 30 días · Uptime 99.9% con SLA · Soporte incluido en todos los planes · Código propietario sin dependencias de terceros · Backups diarios automáticos.", size: "md", color: "#94a3b8", align: "left", maxWidth: "lg" },
        children: [],
        version: 1,
      },
      "process-timeline": {
        id: "process-timeline",
        type: "section",
        props: { maxWidth: "lg", paddingY: "lg", paddingX: "md", align: "left", background: "#172f52", borderRadius: "xl" },
        children: ["process-timeline-title", "process-timeline-copy"],
        version: 1,
        displayName: "Timeline",
      },
      "process-timeline-title": {
        id: "process-timeline-title",
        type: "heading",
        props: { text: "Tiempos de entrega realistas", level: 2, size: "3xl", weight: "bold", color: "#ffffff", align: "left" },
        children: [],
        version: 1,
      },
      "process-timeline-copy": {
        id: "process-timeline-copy",
        type: "text",
        props: { content: "Sitio básico: 24-48h · Sitio avanzado con panel: 3-5 días · Proyecto personalizado con integraciones: 1-2 semanas. Todos los plazos incluyen una ronda de revisiones.", size: "md", color: "#cbd5e1", align: "left", maxWidth: "lg" },
        children: [],
        version: 1,
      },
    },
  },
  portfolio: {
    rootId: "root",
    nodes: {
      root: {
        id: "root",
        type: "section",
        props: { maxWidth: "full", paddingY: "none", paddingX: "none", align: "left", background: "#112540" },
        children: ["portfolio-hero", "portfolio-stats", "portfolio-projects", "portfolio-demos"],
        version: 1,
      },
      "portfolio-hero": {
        id: "portfolio-hero",
        type: "section",
        props: { maxWidth: "xl", paddingY: "xl", paddingX: "md", align: "center", background: "#172f52" },
        children: ["portfolio-eyebrow", "portfolio-title", "portfolio-copy"],
        version: 1,
        displayName: "Hero portafolio",
      },
      "portfolio-eyebrow": {
        id: "portfolio-eyebrow",
        type: "text",
        props: { content: "Portafolio", size: "sm", color: "#00b5f6", align: "center" },
        children: [],
        version: 1,
      },
      "portfolio-title": {
        id: "portfolio-title",
        type: "heading",
        props: { text: "Casos de exito que transforman negocios", level: 1, size: "5xl", weight: "extrabold", color: "#ffffff", align: "center" },
        children: [],
        version: 1,
      },
      "portfolio-copy": {
        id: "portfolio-copy",
        type: "text",
        props: { content: "Más de 150 proyectos entregados en múltiples industrias. Desde negocios locales hasta empresas con decenas de clientes activos en la plataforma.", size: "lg", color: "#cbd5e1", align: "center", maxWidth: "lg" },
        children: [],
        version: 1,
      },
      "portfolio-stats": {
        id: "portfolio-stats",
        type: "section",
        props: { maxWidth: "xl", paddingY: "lg", paddingX: "md", align: "left", background: "#112540" },
        children: ["portfolio-stats-title", "portfolio-stats-copy"],
        version: 1,
        displayName: "Metricas",
      },
      "portfolio-stats-title": {
        id: "portfolio-stats-title",
        type: "heading",
        props: { text: "Números que hablan por sí solos", level: 2, size: "3xl", weight: "bold", color: "#ffffff", align: "left" },
        children: [],
        version: 1,
      },
      "portfolio-stats-copy": {
        id: "portfolio-stats-copy",
        type: "text",
        props: { content: "150+ proyectos completados · 99.9% uptime · Clientes en México, LATAM y España · 4.9/5 satisfacción promedio · Más de 5 años de experiencia en desarrollo web profesional.", size: "md", color: "#94a3b8", align: "left", maxWidth: "lg" },
        children: [],
        version: 1,
      },
      "portfolio-projects": {
        id: "portfolio-projects",
        type: "section",
        props: { maxWidth: "xl", paddingY: "lg", paddingX: "md", align: "left", background: "linear-gradient(180deg, rgba(255,255,255,0.035), rgba(255,255,255,0.02))", border: "1px solid rgba(0,181,246,0.14)", boxShadow: "0 16px 40px rgba(0,0,0,0.18)", borderRadius: "xl" },
        children: ["portfolio-projects-title", "portfolio-projects-copy"],
        version: 1,
        displayName: "Proyectos destacados",
      },
      "portfolio-projects-title": {
        id: "portfolio-projects-title",
        type: "heading",
        props: { text: "Proyectos que generan resultados reales", level: 2, size: "3xl", weight: "bold", color: "#ffffff", align: "left" },
        children: [],
        version: 1,
      },
      "portfolio-projects-copy": {
        id: "portfolio-projects-copy",
        type: "text",
        props: { content: "Despachos legales, contadurías, agencias de viaje, salones de belleza, notarías, consultoras y más. Cada proyecto con su propio panel, dominio y diseño personalizado.", size: "md", color: "#94a3b8", align: "left", maxWidth: "lg" },
        children: [],
        version: 1,
      },
      "portfolio-demos": {
        id: "portfolio-demos",
        type: "section",
        props: { maxWidth: "lg", paddingY: "lg", paddingX: "md", align: "center", background: "#172f52", borderRadius: "xl" },
        children: ["portfolio-demos-title", "portfolio-demos-copy", "portfolio-demos-button"],
        version: 1,
        displayName: "Demos en vivo",
      },
      "portfolio-demos-title": {
        id: "portfolio-demos-title",
        type: "heading",
        props: { text: "Conecta demos y casos reales", level: 2, size: "3xl", weight: "bold", color: "#ffffff", align: "center" },
        children: [],
        version: 1,
      },
      "portfolio-demos-copy": {
        id: "portfolio-demos-copy",
        type: "text",
        props: { content: "Explora demos en vivo de paneles SaaS, dashboards de gestión, tiendas y webs corporativas. Todos construidos con Orvenix y listos para personalizar.", size: "md", color: "#cbd5e1", align: "center", maxWidth: "md" },
        children: [],
        version: 1,
      },
      "portfolio-demos-button": {
        id: "portfolio-demos-button",
        type: "ctaButton",
        props: { label: "Explorar demos", href: "/webs", variant: "secondary" },
        children: [],
        version: 1,
      },
    },
  },
};

function cloneTree(tree: EditorTree): EditorTree {
  return JSON.parse(JSON.stringify(tree)) as EditorTree;
}

export function resolveConstructorPresetId(value: string) {
  if (value in PRESET_TREES) {
    return value as ConstructorPresetId;
  }

  return LEGACY_PRESET_ALIASES[value] ?? null;
}

export function getConstructorPresetTree(sourceFile: string): EditorTree | null {
  const presetId = resolveConstructorPresetId(sourceFile);
  if (!presetId) return null;

  const tree = PRESET_TREES[presetId];
  return tree ? cloneTree(tree) : null;
}

export function isConstructorPresetSource(value: string) {
  return resolveConstructorPresetId(value) !== null;
}

export function getConstructorPresetPreviewHref(value: string) {
  const presetId = resolveConstructorPresetId(value);
  return presetId ? PRESET_PREVIEW_PATHS[presetId] : null;
}
