import type { EditorTree } from "@/types/editor"

/**
 * Landing inicial profesional y 100% editable.
 * Todas las piezas son primitivas del editor: section, heading, text y ctaButton.
 * Cada seccion se puede seleccionar con clic y cada texto se edita con doble clic.
 */
export function buildRichStarterTree(): EditorTree {
  return {
    version: 1,
    rootId: "root",
    theme: {
      colors: {
        primary: "#00b5f6",
        secondary: "#10233d",
        background: "#07101f",
        text: "#e2e8f0",
        accent: "#7dd3fc",
      },
      fontHeading: "Inter",
      fontBody: "Inter",
      spacing: { sectionX: "1.5rem", sectionY: "3.25rem", stack: "1.5rem" },
      radius: { card: "1rem", button: "999px" },
      shadow: {
        soft: "0 18px 44px rgba(8,18,34,0.18)",
        strong: "0 28px 80px rgba(0,0,0,0.34)",
      },
      motion: {
        duration: "240ms",
        easing: "cubic-bezier(0.22, 1, 0.36, 1)",
      },
    },
    seo: {
      title: "Aurea Studio - Crecimiento digital para negocios premium",
      description:
        "Landing profesional editable para presentar servicios, proceso, resultados, planes y contacto.",
      keywords: "consultoria digital, branding, landing page, crecimiento",
      ogImage: "",
    },
    brand: {
      businessName: "Aurea Studio",
      tagline: "Estrategia, diseno y conversion para marcas exigentes",
      description:
        "Estudio boutique que ayuda a negocios profesionales a convertir su presencia digital en oportunidades reales.",
      contact: {
        phone: "+52 55 0000 0000",
        whatsapp: "+52 55 0000 0000",
        email: "hola@aureastudio.mx",
        address: "Ciudad de Mexico",
      },
    },
    nodes: {
      root: {
        id: "root",
        type: "section",
        displayName: "Landing completa editable",
        props: {
          maxWidth: "full",
          paddingY: "none",
          paddingX: "none",
          background: "#07101f",
        },
        children: [
          "hero-section",
          "trust-section",
          "services-section",
          "process-section",
          "proof-section",
          "pricing-section",
          "contact-section",
        ],
        version: 1,
      },

      "hero-section": {
        id: "hero-section",
        type: "section",
        displayName: "Hero principal",
        props: {
          maxWidth: "lg",
          paddingY: "xl",
          paddingX: "md",
          align: "left",
          background:
            "radial-gradient(circle at 12% 18%, rgba(0,181,246,0.26), transparent 34%), linear-gradient(135deg,#07101f 0%,#10233d 54%,#07101f 100%)",
        },
        children: [
          "hero-eyebrow",
          "hero-title",
          "hero-subtitle",
          "hero-primary",
          "hero-secondary",
          "hero-note",
        ],
        version: 1,
      },
      "hero-eyebrow": {
        id: "hero-eyebrow",
        type: "text",
        displayName: "Etiqueta hero",
        props: {
          content: "AUREA STUDIO / CRECIMIENTO DIGITAL",
          size: "sm",
          color: "#7dd3fc",
          align: "left",
        },
        children: [],
        version: 1,
      },
      "hero-title": {
        id: "hero-title",
        type: "heading",
        displayName: "Titulo principal",
        props: {
          text: "Convierte tu sitio en una maquina clara de confianza y ventas",
          level: 1,
          size: "5xl",
          weight: "extrabold",
          color: "#ffffff",
          align: "left",
          marginBottom: "md",
        },
        children: [],
        version: 1,
      },
      "hero-subtitle": {
        id: "hero-subtitle",
        type: "text",
        displayName: "Descripcion hero",
        props: {
          content:
            "Una landing premium para negocios que necesitan explicar su valor, generar credibilidad y llevar al visitante hacia una accion concreta sin ruido.",
          size: "lg",
          color: "#cbd5e1",
          align: "left",
          maxWidth: "lg",
        },
        children: [],
        version: 1,
      },
      "hero-primary": {
        id: "hero-primary",
        type: "ctaButton",
        displayName: "Boton agenda",
        props: {
          label: "Agendar diagnostico",
          href: "#contacto",
          variant: "primary",
          size: "lg",
        },
        children: [],
        version: 1,
      },
      "hero-secondary": {
        id: "hero-secondary",
        type: "ctaButton",
        displayName: "Boton servicios",
        props: {
          label: "Ver servicios",
          href: "#servicios",
          variant: "secondary",
          size: "md",
        },
        children: [],
        version: 1,
      },
      "hero-note": {
        id: "hero-note",
        type: "text",
        displayName: "Nota hero",
        props: {
          content:
            "Diagnostico inicial en 48 horas. Sin plantillas frias, sin promesas vacias.",
          size: "sm",
          color: "#94a3b8",
          align: "left",
          maxWidth: "md",
        },
        children: [],
        version: 1,
      },

      "trust-section": {
        id: "trust-section",
        type: "section",
        displayName: "Barra de confianza",
        props: {
          maxWidth: "lg",
          paddingY: "md",
          paddingX: "md",
          align: "center",
          background: "#0b1729",
          border: "1px solid rgba(125,211,252,0.14)",
          boxShadow: "0 18px 50px rgba(0,0,0,0.18)",
        },
        children: [
          "trust-kicker",
          "trust-title",
          "trust-copy",
          "trust-stat-1",
          "trust-stat-2",
          "trust-stat-3",
        ],
        version: 1,
      },
      "trust-kicker": {
        id: "trust-kicker",
        type: "text",
        displayName: "Etiqueta confianza",
        props: {
          content: "BASE LISTA PARA PERSONALIZAR",
          size: "sm",
          color: "#38bdf8",
          align: "center",
        },
        children: [],
        version: 1,
      },
      "trust-title": {
        id: "trust-title",
        type: "heading",
        displayName: "Titulo confianza",
        props: {
          text: "Una estructura pensada para que el cliente entienda, confie y avance",
          level: 2,
          size: "3xl",
          weight: "extrabold",
          color: "#ffffff",
          align: "center",
          marginBottom: "sm",
        },
        children: [],
        version: 1,
      },
      "trust-copy": {
        id: "trust-copy",
        type: "text",
        displayName: "Texto confianza",
        props: {
          content:
            "Edita textos, colores, botones y secciones para adaptar esta base a cualquier negocio profesional: clinicas, despachos, consultorias, inmobiliarias o servicios premium.",
          size: "md",
          color: "#cbd5e1",
          align: "center",
          maxWidth: "lg",
        },
        children: [],
        version: 1,
      },
      "trust-stat-1": {
        id: "trust-stat-1",
        type: "heading",
        displayName: "Dato 1",
        props: {
          text: "+37% mas solicitudes calificadas",
          level: 3,
          size: "xl",
          weight: "bold",
          color: "#7dd3fc",
          align: "center",
          marginBottom: "sm",
        },
        children: [],
        version: 1,
      },
      "trust-stat-2": {
        id: "trust-stat-2",
        type: "heading",
        displayName: "Dato 2",
        props: {
          text: "Mensaje claro en menos de 8 segundos",
          level: 3,
          size: "xl",
          weight: "bold",
          color: "#7dd3fc",
          align: "center",
          marginBottom: "sm",
        },
        children: [],
        version: 1,
      },
      "trust-stat-3": {
        id: "trust-stat-3",
        type: "heading",
        displayName: "Dato 3",
        props: {
          text: "CTA visible desde el primer bloque",
          level: 3,
          size: "xl",
          weight: "bold",
          color: "#7dd3fc",
          align: "center",
          marginBottom: "none",
        },
        children: [],
        version: 1,
      },

      "services-section": {
        id: "services-section",
        type: "section",
        displayName: "Servicios",
        props: {
          maxWidth: "lg",
          paddingY: "xl",
          paddingX: "md",
          align: "left",
          background: "#f8fafc",
        },
        children: [
          "services-kicker",
          "services-title",
          "services-copy",
          "service-1",
          "service-2",
          "service-3",
        ],
        version: 1,
      },
      "services-kicker": {
        id: "services-kicker",
        type: "text",
        displayName: "Etiqueta servicios",
        props: {
          content: "SERVICIOS PRINCIPALES",
          size: "sm",
          color: "#0284c7",
          align: "left",
        },
        children: [],
        version: 1,
      },
      "services-title": {
        id: "services-title",
        type: "heading",
        displayName: "Titulo servicios",
        props: {
          text: "Tres ofertas faciles de entender y dificiles de ignorar",
          level: 2,
          size: "4xl",
          weight: "extrabold",
          color: "#0f172a",
          align: "left",
          marginBottom: "sm",
        },
        children: [],
        version: 1,
      },
      "services-copy": {
        id: "services-copy",
        type: "text",
        displayName: "Descripcion servicios",
        props: {
          content:
            "Cada servicio esta redactado para vender un resultado, no solo una lista de tareas. Cambia los nombres, beneficios y enlaces segun tu negocio.",
          size: "md",
          color: "#475569",
          align: "left",
          maxWidth: "lg",
        },
        children: [],
        version: 1,
      },
      "service-1": {
        id: "service-1",
        type: "section",
        displayName: "Servicio estrategico",
        props: {
          maxWidth: "lg",
          paddingY: "md",
          paddingX: "md",
          background: "#ffffff",
          border: "1px solid rgba(15,23,42,0.08)",
          borderRadius: "xl",
          shadow: "sm",
        },
        children: ["service-1-title", "service-1-copy"],
        version: 1,
      },
      "service-1-title": {
        id: "service-1-title",
        type: "heading",
        displayName: "Titulo servicio 1",
        props: {
          text: "Diagnostico de posicionamiento",
          level: 3,
          size: "2xl",
          weight: "bold",
          color: "#0f172a",
          align: "left",
          marginBottom: "sm",
        },
        children: [],
        version: 1,
      },
      "service-1-copy": {
        id: "service-1-copy",
        type: "text",
        displayName: "Texto servicio 1",
        props: {
          content:
            "Detectamos que debe decir tu pagina, que objeciones debe resolver y que accion debe provocar para atraer mejores clientes.",
          size: "md",
          color: "#475569",
          align: "left",
        },
        children: [],
        version: 1,
      },
      "service-2": {
        id: "service-2",
        type: "section",
        displayName: "Servicio conversion",
        props: {
          maxWidth: "lg",
          paddingY: "md",
          paddingX: "md",
          background: "#ffffff",
          border: "1px solid rgba(15,23,42,0.08)",
          borderRadius: "xl",
          shadow: "sm",
        },
        children: ["service-2-title", "service-2-copy"],
        version: 1,
      },
      "service-2-title": {
        id: "service-2-title",
        type: "heading",
        displayName: "Titulo servicio 2",
        props: {
          text: "Landing de alto impacto",
          level: 3,
          size: "2xl",
          weight: "bold",
          color: "#0f172a",
          align: "left",
          marginBottom: "sm",
        },
        children: [],
        version: 1,
      },
      "service-2-copy": {
        id: "service-2-copy",
        type: "text",
        displayName: "Texto servicio 2",
        props: {
          content:
            "Construimos una pagina clara, visual y enfocada en conversion: hero, beneficios, prueba social, oferta y contacto.",
          size: "md",
          color: "#475569",
          align: "left",
        },
        children: [],
        version: 1,
      },
      "service-3": {
        id: "service-3",
        type: "section",
        displayName: "Servicio crecimiento",
        props: {
          maxWidth: "lg",
          paddingY: "md",
          paddingX: "md",
          background: "#ffffff",
          border: "1px solid rgba(15,23,42,0.08)",
          borderRadius: "xl",
          shadow: "sm",
        },
        children: ["service-3-title", "service-3-copy"],
        version: 1,
      },
      "service-3-title": {
        id: "service-3-title",
        type: "heading",
        displayName: "Titulo servicio 3",
        props: {
          text: "Optimizacion mensual",
          level: 3,
          size: "2xl",
          weight: "bold",
          color: "#0f172a",
          align: "left",
          marginBottom: "sm",
        },
        children: [],
        version: 1,
      },
      "service-3-copy": {
        id: "service-3-copy",
        type: "text",
        displayName: "Texto servicio 3",
        props: {
          content:
            "Medimos comportamiento, ajustamos mensajes y mejoramos llamados a la accion para aumentar contactos de calidad.",
          size: "md",
          color: "#475569",
          align: "left",
        },
        children: [],
        version: 1,
      },

      "process-section": {
        id: "process-section",
        type: "section",
        displayName: "Proceso",
        props: {
          maxWidth: "lg",
          paddingY: "xl",
          paddingX: "md",
          align: "center",
          background: "#0b1729",
        },
        children: [
          "process-kicker",
          "process-title",
          "process-copy",
          "process-step-1",
          "process-step-2",
          "process-step-3",
        ],
        version: 1,
      },
      "process-kicker": {
        id: "process-kicker",
        type: "text",
        displayName: "Etiqueta proceso",
        props: {
          content: "PROCESO SIMPLE",
          size: "sm",
          color: "#7dd3fc",
          align: "center",
        },
        children: [],
        version: 1,
      },
      "process-title": {
        id: "process-title",
        type: "heading",
        displayName: "Titulo proceso",
        props: {
          text: "De idea a pagina lista sin perder semanas en decisiones",
          level: 2,
          size: "4xl",
          weight: "extrabold",
          color: "#ffffff",
          align: "center",
          marginBottom: "sm",
        },
        children: [],
        version: 1,
      },
      "process-copy": {
        id: "process-copy",
        type: "text",
        displayName: "Descripcion proceso",
        props: {
          content:
            "Este bloque explica como trabajas. Mantiene al prospecto tranquilo porque entiende que pasara despues de contactarte.",
          size: "md",
          color: "#cbd5e1",
          align: "center",
          maxWidth: "lg",
        },
        children: [],
        version: 1,
      },
      "process-step-1": {
        id: "process-step-1",
        type: "heading",
        displayName: "Paso 1",
        props: {
          text: "01 - Brief claro: objetivos, cliente ideal y oferta",
          level: 3,
          size: "xl",
          weight: "bold",
          color: "#7dd3fc",
          align: "center",
          marginBottom: "sm",
        },
        children: [],
        version: 1,
      },
      "process-step-2": {
        id: "process-step-2",
        type: "heading",
        displayName: "Paso 2",
        props: {
          text: "02 - Diseno editable: secciones listas para ajustar",
          level: 3,
          size: "xl",
          weight: "bold",
          color: "#7dd3fc",
          align: "center",
          marginBottom: "sm",
        },
        children: [],
        version: 1,
      },
      "process-step-3": {
        id: "process-step-3",
        type: "heading",
        displayName: "Paso 3",
        props: {
          text: "03 - Publicacion: pagina preparada para recibir leads",
          level: 3,
          size: "xl",
          weight: "bold",
          color: "#7dd3fc",
          align: "center",
          marginBottom: "none",
        },
        children: [],
        version: 1,
      },

      "proof-section": {
        id: "proof-section",
        type: "section",
        displayName: "Caso y testimonios",
        props: {
          maxWidth: "lg",
          paddingY: "xl",
          paddingX: "md",
          align: "left",
          background: "#ffffff",
        },
        children: [
          "proof-kicker",
          "proof-title",
          "proof-copy",
          "proof-quote",
          "proof-author",
        ],
        version: 1,
      },
      "proof-kicker": {
        id: "proof-kicker",
        type: "text",
        displayName: "Etiqueta prueba",
        props: {
          content: "PRUEBA SOCIAL",
          size: "sm",
          color: "#0284c7",
          align: "left",
        },
        children: [],
        version: 1,
      },
      "proof-title": {
        id: "proof-title",
        type: "heading",
        displayName: "Titulo prueba",
        props: {
          text: "Un mensaje mas claro puede cambiar la calidad de tus oportunidades",
          level: 2,
          size: "4xl",
          weight: "extrabold",
          color: "#0f172a",
          align: "left",
          marginBottom: "sm",
        },
        children: [],
        version: 1,
      },
      "proof-copy": {
        id: "proof-copy",
        type: "text",
        displayName: "Texto caso",
        props: {
          content:
            "Antes: visitas sin direccion y mensajes ambiguos. Despues: una oferta directa, pruebas visibles y un camino claro para agendar.",
          size: "md",
          color: "#475569",
          align: "left",
          maxWidth: "lg",
        },
        children: [],
        version: 1,
      },
      "proof-quote": {
        id: "proof-quote",
        type: "text",
        displayName: "Testimonio",
        props: {
          content:
            "\"La pagina dejo de verse bonita solamente. Ahora explica lo que hacemos y nos llegan clientes con mucho mas contexto.\"",
          size: "lg",
          color: "#0f172a",
          align: "left",
          maxWidth: "lg",
        },
        children: [],
        version: 1,
      },
      "proof-author": {
        id: "proof-author",
        type: "text",
        displayName: "Autor testimonio",
        props: {
          content: "Mariana L. - Direccion comercial",
          size: "sm",
          color: "#0284c7",
          align: "left",
        },
        children: [],
        version: 1,
      },

      "pricing-section": {
        id: "pricing-section",
        type: "section",
        displayName: "Oferta",
        props: {
          maxWidth: "md",
          paddingY: "xl",
          paddingX: "md",
          align: "center",
          background:
            "linear-gradient(135deg, rgba(0,181,246,0.16), rgba(125,211,252,0.04)), #0b1729",
        },
        children: [
          "pricing-kicker",
          "pricing-title",
          "pricing-copy",
          "pricing-price",
          "pricing-list",
          "pricing-cta",
        ],
        version: 1,
      },
      "pricing-kicker": {
        id: "pricing-kicker",
        type: "text",
        displayName: "Etiqueta oferta",
        props: {
          content: "OFERTA DESTACADA",
          size: "sm",
          color: "#7dd3fc",
          align: "center",
        },
        children: [],
        version: 1,
      },
      "pricing-title": {
        id: "pricing-title",
        type: "heading",
        displayName: "Titulo oferta",
        props: {
          text: "Paquete de lanzamiento premium",
          level: 2,
          size: "4xl",
          weight: "extrabold",
          color: "#ffffff",
          align: "center",
          marginBottom: "sm",
        },
        children: [],
        version: 1,
      },
      "pricing-copy": {
        id: "pricing-copy",
        type: "text",
        displayName: "Descripcion oferta",
        props: {
          content:
            "Ideal para negocios que necesitan salir con una presencia seria, clara y orientada a capturar contactos desde el primer mes.",
          size: "md",
          color: "#cbd5e1",
          align: "center",
          maxWidth: "md",
        },
        children: [],
        version: 1,
      },
      "pricing-price": {
        id: "pricing-price",
        type: "heading",
        displayName: "Precio editable",
        props: {
          text: "Desde $12,900 MXN",
          level: 3,
          size: "3xl",
          weight: "extrabold",
          color: "#7dd3fc",
          align: "center",
          marginBottom: "sm",
        },
        children: [],
        version: 1,
      },
      "pricing-list": {
        id: "pricing-list",
        type: "text",
        displayName: "Incluye",
        props: {
          content:
            "Incluye estrategia de mensaje, landing editable, copy principal, llamadas a la accion y configuracion lista para publicar.",
          size: "md",
          color: "#e2e8f0",
          align: "center",
          maxWidth: "md",
        },
        children: [],
        version: 1,
      },
      "pricing-cta": {
        id: "pricing-cta",
        type: "ctaButton",
        displayName: "Boton oferta",
        props: {
          label: "Quiero esta estructura",
          href: "#contacto",
          variant: "primary",
          size: "lg",
        },
        children: [],
        version: 1,
      },

      "contact-section": {
        id: "contact-section",
        type: "section",
        displayName: "Contacto final",
        props: {
          maxWidth: "lg",
          paddingY: "xl",
          paddingX: "md",
          align: "center",
          background:
            "radial-gradient(circle at 80% 20%, rgba(0,181,246,0.24), transparent 34%), linear-gradient(135deg,#07101f 0%,#10233d 100%)",
        },
        children: [
          "contact-kicker",
          "contact-title",
          "contact-copy",
          "contact-cta",
          "contact-note",
        ],
        version: 1,
      },
      "contact-kicker": {
        id: "contact-kicker",
        type: "text",
        displayName: "Etiqueta contacto",
        props: {
          content: "SIGUIENTE PASO",
          size: "sm",
          color: "#7dd3fc",
          align: "center",
        },
        children: [],
        version: 1,
      },
      "contact-title": {
        id: "contact-title",
        type: "heading",
        displayName: "Titulo contacto",
        props: {
          text: "Agenda una conversacion y convierte esta base en tu pagina real",
          level: 2,
          size: "4xl",
          weight: "extrabold",
          color: "#ffffff",
          align: "center",
          marginBottom: "sm",
        },
        children: [],
        version: 1,
      },
      "contact-copy": {
        id: "contact-copy",
        type: "text",
        displayName: "Texto contacto",
        props: {
          content:
            "Cambia este bloque por tu telefono, WhatsApp, calendario o formulario. El objetivo es que el visitante sepa exactamente que hacer ahora.",
          size: "lg",
          color: "#cbd5e1",
          align: "center",
          maxWidth: "md",
        },
        children: [],
        version: 1,
      },
      "contact-cta": {
        id: "contact-cta",
        type: "ctaButton",
        displayName: "Boton WhatsApp",
        props: {
          label: "Escribir por WhatsApp",
          href: "https://wa.me/5200000000",
          variant: "primary",
          size: "lg",
        },
        children: [],
        version: 1,
      },
      "contact-note": {
        id: "contact-note",
        type: "text",
        displayName: "Nota contacto",
        props: {
          content:
            "Respuesta en horario laboral. Edita este texto con tus tiempos reales de atencion.",
          size: "sm",
          color: "#94a3b8",
          align: "center",
        },
        children: [],
        version: 1,
      },
    },
  }
}
