"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const node_test_1 = __importDefault(require("node:test"));
const strict_1 = __importDefault(require("node:assert/strict"));
const exportCss_1 = require("../../lib/builder-core/compiler/exportCss");
const theme = {
    colors: {
        primary: "#0ea5e9",
        secondary: "#0f172a",
        background: "#ffffff",
        text: "#111827",
        accent: "#22c55e",
    },
    fontHeading: "Sora, sans-serif",
    fontBody: "Inter, sans-serif",
    spacing: {
        sectionX: "2rem",
        sectionY: "4rem",
        stack: "1.5rem",
    },
    radius: {
        card: "1rem",
        button: "999px",
    },
    shadow: {
        soft: "0 8px 24px rgba(15,23,42,0.08)",
        strong: "0 20px 60px rgba(15,23,42,0.18)",
    },
    motion: {
        duration: "200ms",
        easing: "ease-out",
    },
};
(0, node_test_1.default)("compiler export css builds static export css with shared vars", () => {
    const css = (0, exportCss_1.buildStaticExportCss)(theme);
    strict_1.default.match(css, /Generated by Orvenix Builder/);
    strict_1.default.match(css, /--font-heading: "Sora, sans-serif";/);
    strict_1.default.match(css, /--space-section-y: 4rem;/);
    strict_1.default.match(css, /\.site-nav--pill a\[aria-current="page"\]/);
});
(0, node_test_1.default)("compiler export css builds next globals with tailwind prelude", () => {
    const css = (0, exportCss_1.buildNextExportGlobalsCss)(theme);
    strict_1.default.match(css, /@tailwind base;/);
    strict_1.default.match(css, /:root \{/);
    strict_1.default.match(css, /--primary:\s+#0ea5e9;/);
    strict_1.default.match(css, /\.cta-button/);
    strict_1.default.match(css, /\.orv-block__description/);
});
