import type { GlobalTheme } from "../../../types/editor"

function buildThemeVars(theme: GlobalTheme | null | undefined) {
  if (!theme) {
    return ""
  }

  const colors: Partial<NonNullable<GlobalTheme["colors"]>> = theme.colors ?? {}
  const spacing: Partial<NonNullable<GlobalTheme["spacing"]>> = theme.spacing ?? {}
  const radius: Partial<NonNullable<GlobalTheme["radius"]>> = theme.radius ?? {}
  const shadow: Partial<NonNullable<GlobalTheme["shadow"]>> = theme.shadow ?? {}
  const motion: Partial<NonNullable<GlobalTheme["motion"]>> = theme.motion ?? {}

  return `  --primary:    ${colors.primary ?? "#6366f1"};
  --secondary:  ${colors.secondary ?? "#8b5cf6"};
  --background: ${colors.background ?? "#ffffff"};
  --text:       ${colors.text ?? "#1e293b"};
  --accent:     ${colors.accent ?? "#22c55e"};
  --space-section-x: ${spacing.sectionX ?? "1.5rem"};
  --space-section-y: ${spacing.sectionY ?? "3rem"};
  --space-stack: ${spacing.stack ?? "1.5rem"};
  --radius-card: ${radius.card ?? "1rem"};
  --radius-button: ${radius.button ?? "999px"};
  --shadow-soft: ${shadow.soft ?? "0 12px 32px rgba(15,23,42,0.08)"};
  --shadow-strong: ${shadow.strong ?? "0 24px 60px rgba(15,23,42,0.18)"};
  --motion-duration: ${motion.duration ?? "240ms"};
  --motion-easing: ${motion.easing ?? "cubic-bezier(0.22, 1, 0.36, 1)"};
  --font-heading: ${JSON.stringify(theme.fontHeading ?? "system-ui, sans-serif")};
  --font-body:    ${JSON.stringify(theme.fontBody ?? "system-ui, sans-serif")};`
}

function buildSharedBaseCss() {
  return `body {
  margin: 0;
  font-family: var(--font-body, system-ui, -apple-system, sans-serif);
  background: var(--background, #ffffff);
  color: var(--text, #1e293b);
  line-height: 1.6;
}
h1,h2,h3,h4,h5,h6 {
  font-family: var(--font-heading, system-ui, -apple-system, sans-serif);
  color: var(--text, #1e293b);
}
img {
  max-width: 100%;
  display: block;
}
.cta-button {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: .5rem;
  padding: .85rem 1.2rem;
  border-radius: var(--radius-button, 999px);
  background: var(--primary, #6366f1);
  color: #fff;
  text-decoration: none;
  font-weight: 700;
  box-shadow: var(--shadow-soft, 0 12px 32px rgba(15,23,42,0.08));
  transition: opacity var(--motion-duration, 240ms), transform var(--motion-duration, 240ms);
}
.cta-button--secondary {
  background: transparent;
  color: var(--primary, #6366f1);
  border: 2px solid var(--primary, #6366f1);
}
.orv-block {
  border: 1px dashed rgba(15, 23, 42, 0.14);
  border-radius: var(--radius-card, 1rem);
  padding: 1rem;
  margin: 1rem 0;
  background: rgba(255,255,255,.85);
}
.orv-block__inner {
  display: flex;
  flex-direction: column;
  gap: .35rem;
}
.orv-block__icon { font-size: 1.2rem; }
.orv-block__label {
  font-weight: 700;
  color: var(--text, #1e293b);
}
.orv-block__description {
  color: color-mix(in srgb, var(--text, #1e293b) 72%, white);
  font-size: .95rem;
}
.sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0,0,0,0);
  white-space: nowrap;
  border: 0;
}
.site-nav { width: 100%; }
.site-nav ul {
  list-style: none;
  margin: 0;
  padding: 0;
  display: flex;
  flex-wrap: wrap;
  gap: .5rem;
}
.site-nav--column ul {
  flex-direction: column;
  align-items: flex-start;
}
.site-nav--center ul { justify-content: center; }
.site-nav--end ul { justify-content: flex-end; }
.site-nav a {
  text-decoration: none;
  transition: color .18s ease, border-color .18s ease, background .18s ease;
}
.site-nav--pill a {
  display: inline-flex;
  align-items: center;
  padding: .65rem 1rem;
  border-radius: 999px;
  border: 1px solid rgba(15, 23, 42, 0.12);
  background: rgba(255,255,255,0.86);
  color: var(--text, #1e293b);
}
.site-nav--pill a[aria-current="page"] {
  background: color-mix(in srgb, var(--primary, #6366f1) 14%, white);
  border-color: color-mix(in srgb, var(--primary, #6366f1) 35%, white);
  color: var(--primary, #6366f1);
}
.site-nav--minimal a {
  color: color-mix(in srgb, var(--text, #1e293b) 72%, white);
  padding-bottom: .2rem;
  border-bottom: 1px solid transparent;
}
.site-nav--minimal a[aria-current="page"] {
  color: var(--primary, #6366f1);
  border-color: color-mix(in srgb, var(--primary, #6366f1) 32%, white);
}`
}

export function buildStaticExportCss(theme: GlobalTheme | null | undefined) {
  const vars = buildThemeVars(theme)

  return `/* Generated by Orvenix Builder — orvenix.com.mx */
*, *::before, *::after { box-sizing: border-box; }
${vars ? `body {${vars}
}` : ""}
${buildSharedBaseCss()}`
}

export function buildNextExportGlobalsCss(theme: GlobalTheme | null | undefined) {
  const vars = buildThemeVars(theme)

  return `/* Generated by Orvenix Builder */
@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
${vars}
}

${buildSharedBaseCss()}`
}
