import test from "node:test"
import assert from "node:assert/strict"
import {
  buildNextExportGlobalsCss,
  buildStaticExportCss,
} from "../../lib/builder-core/compiler/exportCss"
import type { GlobalTheme } from "../../types/editor"

const theme: GlobalTheme = {
  colors: {
    primary: "#0ea5e9",
    secondary: "#0f172a",
    background: "#ffffff",
    text: "#111827",
    accent: "#22c55e",
  },
  fontHeading: "Sora, sans-serif",
  fontBody: "Inter, sans-serif",
  spacing: {
    sectionX: "2rem",
    sectionY: "4rem",
    stack: "1.5rem",
  },
  radius: {
    card: "1rem",
    button: "999px",
  },
  shadow: {
    soft: "0 8px 24px rgba(15,23,42,0.08)",
    strong: "0 20px 60px rgba(15,23,42,0.18)",
  },
  motion: {
    duration: "200ms",
    easing: "ease-out",
  },
}

test("compiler export css builds static export css with shared vars", () => {
  const css = buildStaticExportCss(theme)

  assert.match(css, /Generated by Orvenix Builder/)
  assert.match(css, /--font-heading: "Sora, sans-serif";/)
  assert.match(css, /--space-section-y: 4rem;/)
  assert.match(css, /\.site-nav--pill a\[aria-current="page"\]/)
})

test("compiler export css builds next globals with tailwind prelude", () => {
  const css = buildNextExportGlobalsCss(theme)

  assert.match(css, /@tailwind base;/)
  assert.match(css, /:root \{/)
  assert.match(css, /--primary:\s+#0ea5e9;/)
  assert.match(css, /\.cta-button/)
  assert.match(css, /\.orv-block__description/)
})
